# Generated by Django 4.1.2 on 2022-10-08 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="video.video",
                    ),
                ),
                (
                    "chapters",
                    models.SmallIntegerField(default=8, verbose_name="Capitulos"),
                ),
                (
                    "number_season",
                    models.SmallIntegerField(default=1, verbose_name="Temporada"),
                ),
            ],
            options={
                "verbose_name": "Temporada",
                "verbose_name_plural": "Temporadas",
            },
        ),
    ]
