# Generated by Django 4.1.2 on 2022-11-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("season", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="season",
            name="video",
        ),
        migrations.DeleteModel(
            name="HistoricalSeason",
        ),
        migrations.DeleteModel(
            name="Season",
        ),
    ]
