# Generated by Django 4.1.2 on 2022-10-08 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                ("num_year", models.IntegerField(verbose_name="Año")),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "video_type",
                    models.CharField(
                        choices=[
                            ("S", "Serie"),
                            ("M", "Pelicula"),
                            ("D", "Documental"),
                            ("R", "Reality"),
                        ],
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                ("duration", models.IntegerField(blank=True, verbose_name="Duración")),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.classification",
                        verbose_name="Clasificación",
                    ),
                ),
                (
                    "country",
                    models.ManyToManyField(to="core.country", verbose_name="Pais"),
                ),
                (
                    "film_genre",
                    models.ManyToManyField(
                        to="core.filmgenre", verbose_name="Genero Cinematográfico"
                    ),
                ),
                (
                    "provider",
                    models.ManyToManyField(
                        to="core.provider", verbose_name="Proveedor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
            },
        ),
    ]
