# Generated by Django 4.1.2 on 2022-10-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nombre"
            ),
        ),
    ]
